// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoTA_OhlvvNJyavVFVmxGv5GFd0uMT078',
    appId: '1:757887194855:web:bb1c6e25abd9d47876b442',
    messagingSenderId: '757887194855',
    projectId: 'recipebook-b333e',
    authDomain: 'recipebook-b333e.firebaseapp.com',
    storageBucket: 'recipebook-b333e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9u7oK16cUahNniIcaERKv9ytZPqQVk8w',
    appId: '1:757887194855:android:e607f0e679850ecb76b442',
    messagingSenderId: '757887194855',
    projectId: 'recipebook-b333e',
    storageBucket: 'recipebook-b333e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtVxn-p7tbuG8Shha-CpXwSd7zx9hm3Z8',
    appId: '1:757887194855:ios:02440e4f886af14376b442',
    messagingSenderId: '757887194855',
    projectId: 'recipebook-b333e',
    storageBucket: 'recipebook-b333e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationLayoutTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtVxn-p7tbuG8Shha-CpXwSd7zx9hm3Z8',
    appId: '1:757887194855:ios:02440e4f886af14376b442',
    messagingSenderId: '757887194855',
    projectId: 'recipebook-b333e',
    storageBucket: 'recipebook-b333e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationLayoutTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoTA_OhlvvNJyavVFVmxGv5GFd0uMT078',
    appId: '1:757887194855:web:654db626ed6dfb9676b442',
    messagingSenderId: '757887194855',
    projectId: 'recipebook-b333e',
    authDomain: 'recipebook-b333e.firebaseapp.com',
    storageBucket: 'recipebook-b333e.firebasestorage.app',
  );
}
